doctrine:
  orm:
    auto_mapping: false
    mappings:
      PermissionsManagerBundle:
        is_bundle: true
        dir: '%kernel.root_dir%/../../src/Entity'
        prefix: 'PermissionsManagerBundle\Entity'
        alias: PermissionsManagerBundle
