doctrine:
  orm:
    auto_mapping: true
    mappings:
      PermissionsManagerBundle:
        type: annotation
        is_bundle: true
        dir: '%kernel.root_dir%/../../src/Entity'
        prefix: 'DabrosDkos\PermissionsManagerBundle\Entity'
        alias: PermissionsManagerBundle
