doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
    resolve_target_entities:
      - DabrosDkos\PermissionsManagerBundle\Entity\Test
    auto_mapping: true
    mappings:
      App:
        is_bundle: true
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'DabrosDkos\PermissionsManagerBundle\Entity'
        alias: PermissionsManagerBundle
