dabros_resource:
  resources:
    app.permissions-manager-bundle.roles:
      driver: doctrine/orm
      classes:
        model: DabrosDkos\PermissionsManagerBundle\Entity\PmRoles
        repository: DabrosDkos\PermissionsManagerBundle\Repository\PmRolesRepository
    app.permissions-manager-bundle.group:
      driver: doctrine/orm
      classes:
        model: DabrosDkos\PermissionsManagerBundle\Entity\PmGroup
        repository: DabrosDkos\PermissionsManagerBundle\Repository\PmGroupRepository
