dabros_resource:
  resources:
    permissions-manager-bundle-roles:
      driver: doctrine/orm
      classes:
        model: DabrosDkos\PermissionsManagerBundle\Entity\PmRoles
        repository: DabrosDkos\PermissionsManagerBundle\Repository\PmRolesRepository
