doctrine:
  orm:
    mappings:
      PermissionsManagerBundle:
        is_bundle: false
        type: annotation
        dir: '../../src/Entity'
        prefix: 'DabrosDkos\PermissionsManagerBundle\Entity'
        alias: PermissionsManagerBundle
